In [17]:
import pandas as pd
import numpy as np

In [18]:
FILEPATH = "Y:/Members_Current/Jenn/EEG study/Imported data/cleaned/"
participants = ["105", "106", "107", "904", "905", "906"]

from ml_prep import prep_ml
X,y = prep_ml(FILEPATH, participants)

In [19]:
# 1 and 2 are animates, 3 and 4 are inanimates
y[y <= 2] = 0
y[y > 2] = 1

In [20]:
(n, d) = X.shape
assert n == y.shape[0]

In [21]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [22]:
# from sklearn.svm import SVC
# model = SVC(gamma='auto', kernel='linear')
# model.fit(X_train, y_train)

In [23]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

c:\users\karl\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
Xhat = model.predict(X_test)

In [25]:
np.mean(Xhat != y_test)

0.4473684210526316

In [26]:
Xhat

array([1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0.])

In [27]:
y_test

array([1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 1.])

In [28]:
np.mean(model.predict(X_train) != y_train)

0.006711409395973154

In [29]:
Xhat != y_test

array([False,  True,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False,  True, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True, False,
        True,  True])

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, Xhat))

              precision    recall  f1-score   support

         0.0       0.56      0.75      0.64        20
         1.0       0.55      0.33      0.41        18

    accuracy                           0.55        38
   macro avg       0.55      0.54      0.53        38
weighted avg       0.55      0.55      0.53        38

