In [1]:
import pandas as pd
import numpy as np

In [2]:
FILEPATH = "Y:/Members_Current/Jenn/EEG study/Imported data/cleaned/"
participants = ["105", "106", "107", "904", "905", "906"]

from ml_prep import prep_ml
X,y = prep_ml(FILEPATH, participants)

In [3]:
y

array([4., 2., 3., 1., 4., 2., 3., 1., 4., 1., 3., 2., 3., 1., 4., 2., 3.,
       2., 4., 1., 4., 2., 3., 1., 4., 1., 3., 2., 4., 1., 3., 2., 4., 2.,
       3., 1., 4., 1., 3., 2., 4., 1., 3., 2., 4., 2., 2., 4., 1., 3., 1.,
       3., 2., 4., 2., 4., 1., 3., 1., 4., 2., 3., 2., 3., 1., 4., 2., 3.,
       1., 4., 2., 4., 1., 3., 1., 4., 2., 3., 3., 2., 4., 1., 4., 1., 3.,
       2., 4., 1., 3., 2., 3., 2., 4., 1., 3., 2., 4., 1., 3., 2., 4., 1.,
       3., 2., 4., 1., 3., 1., 4., 2., 3., 1., 4., 2., 4., 1., 3., 2., 3.,
       2., 4., 1., 4., 1., 3., 2., 4., 2., 3., 1., 4., 1., 3., 2., 4., 2.,
       3., 1., 3., 1., 4., 2., 4., 2., 3., 1., 4., 1., 3., 2., 3., 1., 4.,
       2., 3., 1., 4., 2., 3., 1., 4., 2., 3., 1., 4., 2., 3., 2., 4., 1.,
       4., 2., 3., 1., 3., 2., 4., 1., 4., 2., 3., 1., 3., 2., 4., 1., 3.,
       2., 4., 1., 3., 2., 3., 1., 4., 1., 3., 2., 4., 2., 4., 1., 3., 1.,
       3., 2., 4., 2., 4., 1., 3., 2., 4., 1., 3., 2., 3., 1., 4., 2., 3.,
       1., 4., 1., 4., 2.

In [4]:
y[y<=2] = 0
y[y>2] = 1
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0.

In [5]:
(n, d) = X.shape
assert n == y.shape[0]

In [6]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [7]:
# from sklearn.svm import SVC
# model = SVC(gamma='auto', kernel='linear')
# model.fit(X_train, y_train)

In [8]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

c:\users\karl\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [9]:
Xhat = model.predict(X_test)

In [10]:
np.mean(Xhat != y_test)

0.45054945054945056

In [11]:
Xhat

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0.])

In [12]:
y_test


array([0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 1., 1., 1., 0.])

In [13]:
np.mean(model.predict(X_train) != y_train)

0.00554016620498615

In [14]:
Xhat != y_test

array([False,  True, False, False,  True,  True,  True, False,  True,
       False, False, False, False,  True, False, False,  True,  True,
       False,  True,  True,  True, False, False, False, False, False,
       False, False, False, False,  True, False,  True,  True, False,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False, False,  True, False,  True, False,  True, False,  True,
       False,  True, False, False, False, False,  True, False,  True,
        True, False, False, False, False,  True, False,  True,  True,
        True, False,  True,  True, False,  True,  True,  True, False,
        True,  True, False, False, False,  True,  True, False, False,
       False])

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test, Xhat))

              precision    recall  f1-score   support

         0.0       0.57      0.55      0.56        47
         1.0       0.53      0.55      0.54        44

    accuracy                           0.55        91
   macro avg       0.55      0.55      0.55        91
weighted avg       0.55      0.55      0.55        91

