In [27]:
import pandas as pd
import numpy as np

In [28]:
from constants import cleaned_data_filepath
participants = ["107", "904", "905", "906"]

from ml_prep import prep_ml
X,y,p,w = prep_ml(cleaned_data_filepath, participants, downsample_num=200, averaging="average_trials_and_participants")
for x in range(len(X)): 
    print(X[x])

[0.03580066 0.03580066 0.03580066 ... 0.03580066 0.03580066 0.03580066]
[0. 0. 0. ... 0. 0. 0.]
[-0.24644155 -0.24644155 -0.24644155 ... -0.24644155 -0.24644155
 -0.24644155]
[0. 0. 0. ... 0. 0. 0.]
[-0.04095134 -0.04095134 -0.04095134 ... -0.04095134 -0.04095134
 -0.04095134]
[0.03777912 0.03777912 0.03777912 ... 0.03777912 0.03777912 0.03777912]
[0.05511384 0.05511384 0.05511384 ... 0.05511384 0.05511384 0.05511384]
[-0.02006319 -0.02006319 -0.02006319 ... -0.02006319 -0.02006319
 -0.02006319]
[-0.1902079 -0.1902079 -0.1902079 ... -0.1902079 -0.1902079 -0.1902079]
[0.1967419 0.1967419 0.1967419 ... 0.1967419 0.1967419 0.1967419]
[-0.06509225 -0.06509225 -0.06509225 ... -0.06509225 -0.06509225
 -0.06509225]
[-0.16430205 -0.16430205 -0.16430205 ... -0.16430205 -0.16430205
 -0.16430205]
[0. 0. 0. ... 0. 0. 0.]
[-0.01691592 -0.01691592 -0.01691592 ... -0.01691592 -0.01691592
 -0.01691592]
[-0.12557656 -0.12557656 -0.12557656 ... -0.12557656 -0.12557656
 -0.12557656]
[0. 0. 0. ... 0. 0. 0

In [29]:
y.shape[0]

16

In [30]:
(n, d) = X.shape
assert n == y.shape[0]

In [31]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [32]:
# from eval import eval_across_participants
# errs = eval_across_participants(model, X, y, p, 1000, random_state=50)
# print("\n---\n")
# for j in range(errs.shape[0]):
#   print(np.mean(errs[j, :]))

In [33]:
from eval import eval_normal
errs = eval_normal(model, X, y, 1000, random_state=0)


[                    ] 0%

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[====================] 100%

In [34]:
np.mean(errs)

0.5305