In [3]:
import pandas as pd
import numpy as np

In [4]:
from constants import cleaned_data_filepath
participants = ["107", "904", "905", "906"]

from ml_prep import prep_ml
X,y,p,w,df = prep_ml(cleaned_data_filepath, participants, downsample_num=200, averaging="no_averaging")

In [15]:
Xp,yp,pp,wp,df2 = prep_ml(cleaned_data_filepath, participants, downsample_num=200, averaging="average_trials")

C:\Users\Karl\Documents\jwlab_eeg\code\jwlab_eeg\classification\ml_prep.py:81: RuntimeWarning: Mean of empty slice.
  means = df_data[np.logical_and(df.participant == p, df.label == w)].values.mean()
c:\users\karl\appdata\local\programs\python\python37\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [6]:
(n, d) = X.shape
assert n == y.shape[0]

In [7]:
from sklearn.svm import LinearSVC
model = LinearSVC(C=1e-6, max_iter=10000)

In [8]:
# from sklearn.ensemble import BaggingClassifier
# model = BaggingClassifier(model)

In [9]:
# from sklearn.model_selection import GridSearchCV

# param_grid = [
  # {'C': np.logspace(-10, -5, 3)}
 # ]

# tuned_model = GridSearchCV(model, param_grid)
# tuned_model.fit(X, y)

# tuned_model.cv_results_

In [10]:
# from sklearn import preprocessing

# scaler = preprocessing.StandardScaler().fit(X)
# X,Xp = scaler.transform(X), scaler.transform(Xp)

model.fit(X, y)
np.mean(model.predict(Xp) != yp)

0.44680851063829785

In [11]:
y

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [12]:
yp

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [13]:
model.predict(Xp)

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1])

In [14]:
len(yp)

47