In [57]:
import pandas as pd
import numpy as np

In [58]:
FILEPATH = "/Volumes/OFFCAMPUS/Jenn/Imported data/cleaned/"
participants = ["105", "106", "107", "904", "905", "906"]

dfs = [pd.read_csv("%s%s_cleaned_ml.csv" % (FILEPATH, s)) for s in participants]

df = pd.concat(dfs, axis=0, ignore_index=True)

In [96]:
df

Time          E1        E2         E3         E4         E5  \
0      -200.0   13.649351  4.253679   9.996485   9.481434  18.026508   
1      -199.0   13.828758  4.976443  10.084705   9.582227  18.480547   
2      -198.0   14.142060  5.850959  10.178824   9.686580  19.001780   
3      -197.0   14.560205  6.793514  10.284312   9.803214  19.552628   
4      -196.0   15.053234  7.721226  10.407560   9.938207  20.092878   
...       ...         ...       ...        ...        ...        ...   
542395  995.0 -233.694122  7.769695   8.263282 -34.424835  74.074875   
542396  996.0 -233.596756  7.821805   7.365407 -35.303608  73.046166   
542397  997.0 -233.481140  7.782219   6.621273 -36.059338  70.529800   
542398  998.0 -233.399612  7.643509   6.047417 -36.694870  66.741524   
542399  999.0 -233.405914  7.419993   5.654030 -37.219276  61.962593   

               E6         E7         E8         E9  ...        E56        E57  \
0        5.564005  12.778870   1.174925  13.478706  ...  -2.362542  -0.461481   
1        5.537510  12.838730   1.211721  13.147108  ...  -3.272416  -0.463592   
2        5.393631  12.747041   1.206468  12.338480  ...  -4.002994  -0.402802   
3        5.139943  12.524466   1.158097  11.103312  ...  -4.511529  -0.304838   
4        4.792314  12.198002   1.070401   9.519570  ...  -4.765975  -0.191731   
...           ...        ...        ...        ...  ...        ...        ...   
542395  16.008013 -66.621674  28.767864  18.601503  ... -51.375248 -27.745144   
542396  15.163234 -67.140457  28.350851  17.708069  ... -51.273594 -28.642437   
542397  14.454845 -67.453232  27.820776  17.149921  ... -51.154018 -29.295010   
542398  13.892268 -67.572365  27.217438  16.867893  ... -51.033100 -29.711704   
542399  13.475890 -67.528046  26.588888  16.776771  ... -50.918606 -29.912426   

              E58        E59       E60         E61         E62        E63  \
0       -9.263395  -2.207499  3.446589   -3.198227   -3.198227  -3.198227   
1      -10.913692  -2.212922  3.910747   -3.019854   -3.019854  -3.019854   
2      -11.890976  -2.120070  4.458347   -2.751333   -2.751333  -2.751333   
3      -12.029873  -1.959178  5.037091   -2.393907   -2.393907  -2.393907   
4      -11.221484  -1.756361  5.597899   -1.954948   -1.954948  -1.954948   
...           ...        ...       ...         ...         ...        ...   
542395 -11.294678  14.642734  4.838850 -120.415878 -152.254807  22.633812   
542396 -10.040168  15.589846  4.592117 -121.814385 -147.267349  25.017849   
542397  -9.149659  16.343340  4.526050 -123.629273 -143.011612  29.931921   
542398  -8.681676  16.838526  4.602078 -125.815170 -139.802063  36.825619   
542399  -8.662592  17.035040  4.785510 -128.288773 -137.849853  44.995388   

              E64        E65  
0       -3.198227  -3.198227  
1       -3.019854  -3.019854  
2       -2.751333  -2.751333  
3       -2.393907  -2.393907  
4       -1.954948  -1.954948  
...           ...        ...  
542395  66.947205  74.557816  
542396  67.780792  74.212090  
542397  68.535294  74.022133  
542398  69.078316  73.987007  
542399  69.285149  74.097336  

[542400 rows x 66 columns]

In [59]:
# samples are df rows mod 1200, pre is 0-199, post is 200-1199

# extract pre rows and post rows, randomly choose 200-400ms as post
pre = df[df.Time < 0]
post = df[df.Time >= 200][df.Time < 400]

c:\users\karl\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """


In [60]:
pre = pre.drop(columns=["Time", "E65"], axis=1)
post = post.drop(columns=["Time", "E65"], axis=1)

In [61]:
timeFrame = 200

preX = pre.values
(i,j) = preX.shape
preX = np.reshape(preX, (i // 200, j * 200))

In [62]:
postX = post.values
(i,j) = postX.shape
postX = np.reshape(postX, (i // 200, j * 200))

In [63]:
(preN, preD) = preX.shape
(postN, postD) = postX.shape

In [64]:
X = np.concatenate((preX, postX), axis=0)
(n, d) = X.shape
assert(n == preN + postN)
assert(d == postD)
assert(d == preD)

In [65]:
y = np.concatenate((np.zeros(preN), np.ones(postN)))
assert(y.shape == (n,))

In [66]:
# just use this : on next one
# from sklearn.model_selection import train_test_split 

rand_indices = np.random.permutation(n)
split = int(n * 0.8)
train_idx, valid_idx = rand_indices[:split], rand_indices[split:]
train_X, valid_X, train_y, valid_y = X[train_idx, :], X[valid_idx, :], y[train_idx], y[valid_idx]

In [67]:
# from sklearn.svm import SVC
# model = SVC(gamma='auto', kernel='linear')
# model.fit(train_X, train_y)

In [87]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(train_X, train_y)

c:\users\karl\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [88]:
# from sklearn.neighbors import KNeighborsClassifier
# from dtw import DTW

# model = KNeighborsClassifier(metric=DTW)
# model.fit(train_X, train_y)

In [89]:
Xhat = model.predict(valid_X)

In [90]:
np.mean(Xhat != valid_y)

0.07734806629834254

In [91]:
Xhat

array([1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.])

In [92]:
valid_y

array([1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.])

In [93]:
np.mean(model.predict(train_X) != train_y)

0.0027662517289073307

In [94]:
Xhat != valid_y

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False,

In [95]:
from sklearn.metrics import classification_report
print(classification_report(valid_y, Xhat))

              precision    recall  f1-score   support

         0.0       0.90      0.96      0.93        98
         1.0       0.95      0.88      0.91        83

    accuracy                           0.92       181
   macro avg       0.93      0.92      0.92       181
weighted avg       0.92      0.92      0.92       181

