In [1]:
import setup_jwlab
import pandas as pd
import numpy as np

from jwlab.ml_prep import load_ml_df, y_to_binary
from sklearn.model_selection import cross_val_score

In [2]:
df = load_ml_df("~/projects/def-jwerker/kjslakov/data/ml_df_sktime.pkl")

In [3]:
df.head()

0  \
0  0     -13.517964
1     -14.678286
2     -15.61...   
1  0      -6.267445
1      -7.005262
2      -7.99...   
2  0      -5.051580
1      -5.461963
2      -5.90...   
3  0      -5.336224
1      -6.826965
2      -8.11...   
4  0      14.368332
1      14.469492
2      14.53...   

                                                   1  \
0  0      22.010553
1      24.132185
2      25.29...   
1  0     -10.671413
1     -10.621878
2     -10.51...   
2  0     -10.781385
1      -9.655065
2      -8.24...   
3  0       8.902582
1      10.481461
2      11.99...   
4  0      -7.143710
1      -7.472065
2      -7.56...   

                                                   2  \
0  0      10.012394
1      10.566473
2      11.10...   
1  0       0.578791
1       1.328545
2       2.02...   
2  0      0.190376
1      0.084128
2      0.00033...   
3  0      1.747106
1      3.413296
2      5.12646...   
4  0      -1.941029
1      -1.908351
2      -1.78...   

                                                   3  \
0  0      21.608709
1      20.250221
2      18.85...   
1  0      11.550019
1      12.399916
2      13.07...   
2  0      1.368724
1      0.850300
2      0.26416...   
3  0      -3.788313
1      -2.789180
2      -1.88...   
4  0      -4.037873
1      -3.787118
2      -3.47...   

                                                   4  \
0  0      -47.938713
1      -45.505158
2      -40...   
1  0     -22.521195
1     -21.941107
2     -21.31...   
2  0       5.463544
1       4.818605
2       3.56...   
3  0       2.612656
1       0.173693
2      -2.45...   
4  0     -16.169552
1     -14.211832
2     -11.72...   

                                                   5  \
0  0       3.326609
1       2.009358
2       0.79...   
1  0      10.500483
1      11.383019
2      12.07...   
2  0      7.725687
1      7.486259
2      7.12549...   
3  0     -6.873928
1     -5.907692
2     -4.95398...   
4  0       3.893104
1       4.417121
2       5.03...   

                                                   6  \
0  0      16.604321
1      15.843433
2      15.19...   
1  0      21.748081
1      21.454708
2      21.02...   
2  0     -3.148193
1     -3.677819
2     -4.30081...   
3  0     -16.138010
1     -15.696688
2     -15.34...   
4  0     -8.895123
1     -8.163536
2     -7.44862...   

                                                   7  \
0  0      -2.932594
1      -4.512460
2      -5.73...   
1  0      4.407655
1      5.182968
2      5.81885...   
2  0      11.126657
1      10.988057
2      10.61...   
3  0     -10.887217
1     -10.231867
2      -9.52...   
4  0       2.405070
1       3.120389
2       4.01...   

                                                   8  \
0  0       7.207326
1       5.404457
2       3.64...   
1  0      17.857426
1      18.479494
2      18.85...   
2  0      9.978209
1      9.160437
2      8.25831...   
3  0     -13.439786
1     -13.008655
2     -12.60...   
4  0      -0.573063
1       0.027385
2       0.63...   

                                                   9  ...  \
0  0     -30.335497
1     -37.856235
2     -45.52...  ...   
1  0     -62.065185
1     -65.034737
2     -67.69...  ...   
2  0      12.743648
1      17.947557
2      22.51...  ...   
3  0      -9.340491
1     -10.149594
2     -11.05...  ...   
4  0     -19.320463
1     -19.727423
2     -19.29...  ...   

                                                  51  \
0  0      7.740145
1      8.823746
2      9.45519...   
1  0      -2.957016
1      -2.409596
2      -1.92...   
2  0       8.736267
1       7.897930
2       7.06...   
3  0     -33.305260
1     -34.575096
2     -35.23...   
4  0       2.925353
1       4.071042
2       5.08...   

                                                  52  \
0  0      27.605501
1      27.934628
2      28.05...   
1  0     -15.052962
1     -14.712629
2     -14.19...   
2  0     -5.918347
1     -6.927714
2     -7.89982...   
3  0       2.213375
1       3.245856
2       4.36...   
4  0      3.961796
1      3.402988

In [3]:
y = y_to_binary(df.label.values.flatten())
df = df.drop(columns=["label"], axis=1)

In [39]:
from scipy.stats import entropy, kurtosis, skew
funcs = [np.mean, np.min, np.max, np.var, skew, kurtosis]
dfs_applied = [df.applymap(f) for f in funcs]

In [43]:
from functools import reduce

suffix = 0
def join_dfs(a, b):
    global suffix
    suffix = suffix + 1
    return a.join(b, rsuffix="_%d" % suffix)

df_concat = reduce(join_dfs, dfs_applied)

In [46]:
df_concat.head()

0          1          2          3          4          5  \
0   9.619437  26.061406  21.843268  18.845386 -47.679006   5.239017   
1   6.853466   0.348400  12.250030  23.596510  -1.851088  16.716675   
2 -18.879231  -4.448306   1.029752   4.498039 -19.878193  -1.135712   
3  13.288054 -14.234266 -16.283855 -17.121040 -11.281634  -9.797145   
4  20.522480  -3.583972   2.115232  13.712213  10.745049  12.048008   

           6          7          8          9  ...      50_5      51_5  \
0  17.645599  20.143882   8.135744 -13.110967  ... -0.497949 -0.062220   
1  21.320742   7.950176  19.992376   9.125198  ... -0.272569  0.206072   
2   7.389829  -7.171245   6.062628 -22.587683  ... -0.505275 -0.155466   
3 -23.788907   5.723077 -19.165705   3.194474  ... -1.065180 -0.954361   
4  15.790093   5.775336   9.180519  16.967114  ...  0.085160 -0.273314   

       52_5      53_5      54_5      55_5      56_5      57_5      58_5  \
0  0.556089  0.207745 -0.991521  0.140063  0.106007  0.284390 -0.236736   
1 -0.382334 -0.990482  0.235168  0.997987  0.129002  0.659618 -0.441390   
2 -0.350456 -0.397194 -0.081773 -0.802797 -0.756513 -0.491387 -0.205341   
3 -0.093076 -1.284191 -0.406945 -0.711584  0.845993 -0.801256 -0.368082   
4  0.009561  0.023627 -0.948572 -0.951845 -1.008065 -0.995915 -0.460662   

       59_5  
0 -0.558785  
1  0.171510  
2 -0.836175  
3  0.281464  
4 -0.687331  

[5 rows x 360 columns]

In [47]:
df_normalized = (df_concat - df_concat.mean()) / df_concat.std()
df_normalized.head()

0         1         2         3         4         5         6  \
0  0.176785  1.170234  1.116690  0.668880 -0.988135  0.160344  0.757075   
1  0.101716 -0.021843  0.602478  0.841018 -0.099454  0.725952  0.930545   
2 -0.596683 -0.244222  0.001055  0.149059 -0.449030 -0.153796  0.272994   
3  0.276354 -0.697907 -0.926980 -0.634224 -0.282329 -0.580624 -1.198670   
4  0.472700 -0.204151  0.059238  0.482899  0.144806  0.495885  0.669494   

          7         8         9  ...      50_5      51_5      52_5      53_5  \
0  0.786278  0.313916 -0.124054  ... -0.165345  0.247435  1.042874  0.704756   
1  0.236801  0.943036 -0.005292  ...  0.049830  0.544398 -0.071461 -0.807093   
2 -0.444606  0.203915 -0.174668  ... -0.172339  0.144225 -0.033607 -0.058519   
3  0.136443 -1.134714 -0.036968  ... -0.706891 -0.740044  0.272020 -1.177677   
4  0.138797  0.369353  0.036591  ...  0.391362  0.013783  0.393896  0.472447   

       54_5      55_5      56_5      57_5      58_5      59_5  
0 -0.696690  0.610625  0.458073  0.313420 -0.028643 -0.400936  
1  0.609970  1.835462  0.486554  0.537516 -0.273783  0.448293  
2  0.272367 -0.735472 -0.610238 -0.149892  0.008962 -0.723500  
3 -0.074004 -0.605250  1.374613 -0.334953 -0.185973  0.576152  
4 -0.650941 -0.948265 -0.921809 -0.451209 -0.296869 -0.550416  

[5 rows x 360 columns]

In [48]:
from sklearn.svm import LinearSVC
model = LinearSVC(max_iter=10000)

scores = cross_val_score(model, df_normalized, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.5177305  0.4822695  0.53191489 0.44680851 0.48201439]
Accuracy: 0.49 (+/- 0.06)


In [49]:
from sklearn.svm import SVC
model = SVC(gamma='scale')

scores = cross_val_score(model, df_concat, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.5035461  0.5035461  0.5035461  0.5035461  0.50359712]
Accuracy: 0.50 (+/- 0.00)


In [50]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
scores = cross_val_score(model, df_concat, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.53191489 0.43262411 0.43971631 0.5035461  0.45323741]
Accuracy: 0.47 (+/- 0.08)


In [51]:
from sktime.classifiers.compose import TimeSeriesForestClassifier
from sktime.classifiers.dictionary_based.boss import BOSSEnsemble
from sktime.classifiers.compose import ColumnEnsembleClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2)

model = ColumnEnsembleClassifier(estimators=[
    ("TSF0", TimeSeriesForestClassifier(n_estimators=5), [0]),
    ("BOSSEnsemble3", BOSSEnsemble(ensemble_size=3), [3]),
])
# model.fit(X_train, y_train)
# print(np.mean(model.predict(X_test) != y_test))

In [ ]:
from sktime.classifiers.shapelet_based import ShapeletTransformClassifier

clf = ShapeletTransformClassifier(time_contract_in_mins=0.5)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)