In [13]:
import setup_jwlab
import pandas as pd
import numpy as np

from jwlab.ml_prep import load_ml_df, y_to_binary
from sklearn.model_selection import cross_val_score

In [14]:
df = load_ml_df("~/projects/def-jwerker/kjslakov/data/ml_df_sktime.pkl")
df_2 = load_ml_df("~/projects/def-jwerker/kjslakov/data/ml_df_readys.pkl")

In [15]:
df.head()

0  \
0  0      -6.267445
1      -7.005262
2      -7.99...   
1  0      -5.051580
1      -5.461963
2      -5.90...   
2  0      -5.336224
1      -6.826965
2      -8.11...   
3  0      14.368332
1      14.469492
2      14.53...   
4  0       5.921907
1       6.174763
2       6.16...   

                                                   1  \
0  0     -10.671413
1     -10.621878
2     -10.51...   
1  0     -10.781385
1      -9.655065
2      -8.24...   
2  0       8.902582
1      10.481461
2      11.99...   
3  0      -7.143710
1      -7.472065
2      -7.56...   
4  0       7.394731
1       8.078009
2       9.03...   

                                                   2  \
0  0       0.578791
1       1.328545
2       2.02...   
1  0      0.190376
1      0.084128
2      0.00033...   
2  0      1.747106
1      3.413296
2      5.12646...   
3  0      -1.941029
1      -1.908351
2      -1.78...   
4  0      11.163538
1      11.723199
2      12.21...   

                                                   3  \
0  0      11.550019
1      12.399916
2      13.07...   
1  0      1.368724
1      0.850300
2      0.26416...   
2  0      -3.788313
1      -2.789180
2      -1.88...   
3  0      -4.037873
1      -3.787118
2      -3.47...   
4  0       6.190385
1       7.438057
2       8.60...   

                                                   4  \
0  0     -22.521195
1     -21.941107
2     -21.31...   
1  0       5.463544
1       4.818605
2       3.56...   
2  0       2.612656
1       0.173693
2      -2.45...   
3  0     -16.169552
1     -14.211832
2     -11.72...   
4  0      14.727507
1      17.044849
2      18.88...   

                                                   5  \
0  0      10.500483
1      11.383019
2      12.07...   
1  0      7.725687
1      7.486259
2      7.12549...   
2  0     -6.873928
1     -5.907692
2     -4.95398...   
3  0       3.893104
1       4.417121
2       5.03...   
4  0      14.143522
1      14.617286
2      14.91...   

                                                   6  \
0  0      21.748081
1      21.454708
2      21.02...   
1  0     -3.148193
1     -3.677819
2     -4.30081...   
2  0     -16.138010
1     -15.696688
2     -15.34...   
3  0     -8.895123
1     -8.163536
2     -7.44862...   
4  0      0.216328
1      1.093795
2      1.86052...   

                                                   7  \
0  0      4.407655
1      5.182968
2      5.81885...   
1  0      11.126657
1      10.988057
2      10.61...   
2  0     -10.887217
1     -10.231867
2      -9.52...   
3  0       2.405070
1       3.120389
2       4.01...   
4  0      16.065905
1      16.452812
2      16.59...   

                                                   8  \
0  0      17.857426
1      18.479494
2      18.85...   
1  0      9.978209
1      9.160437
2      8.25831...   
2  0     -13.439786
1     -13.008655
2     -12.60...   
3  0      -0.573063
1       0.027385
2       0.63...   
4  0      22.855539
1      23.997120
2      24.73...   

                                                   9  ...  \
0  0     -62.065185
1     -65.034737
2     -67.69...  ...   
1  0      12.743648
1      17.947557
2      22.51...  ...   
2  0      -9.340491
1     -10.149594
2     -11.05...  ...   
3  0     -19.320463
1     -19.727423
2     -19.29...  ...   
4  0     -21.799381
1     -14.258102
2      -5.75...  ...   

                                                  51  \
0  0      -2.957016
1      -2.409596
2      -1.92...   
1  0       8.736267
1       7.897930
2       7.06...   
2  0     -33.305260
1     -34.575096
2     -35.23...   
3  0       2.925353
1       4.071042
2       5.08...   
4  0       6.260407
1       6.844238
2       7.31...   

                                                  52  \
0  0     -15.052962
1     -14.712629
2     -14.19...   
1  0     -5.918347
1     -6.927714
2     -7.89982...   
2  0       2.213375
1       3.245856
2       4.36...   
3  0      3.961796
1      3.402988
2      2.83145...   
4  0      -3.398882
1      -3.2385

In [16]:
df = df[df_2.participant.values >= 6]
y = y_to_binary(df.label.values.flatten())
df = df.drop(columns=["label"], axis=1)

In [17]:
np.mean(y == 0)

0.5140562248995983

In [18]:
from scipy.stats import entropy, kurtosis, skew
funcs = [np.mean, np.min, np.max, np.var, skew, kurtosis]
dfs_applied = [df.applymap(f) for f in funcs]

In [19]:
from functools import reduce

suffix = 0
def join_dfs(a, b):
    global suffix
    suffix = suffix + 1
    return a.join(b, rsuffix="_%d" % suffix)

df_concat = reduce(join_dfs, dfs_applied)

In [20]:
df_concat.head()

0          1          2          3          4          5  \
404  13.436086  10.809360   4.132970  -3.255223  13.241646   1.188643   
405  18.357580  20.300056  14.502223   6.301174  19.874719  10.957256   
406   3.364870   5.914619   4.045266   2.934727   4.181210   1.886064   
407   2.302415   6.574074  19.619080  15.802355  12.869702  18.063911   
408  10.629187   0.855701   7.795389  16.258768   5.020757  10.655664   

             6          7          8          9  ...      50_5      51_5  \
404   0.267040  -0.376862   1.726114   0.922727  ... -0.005173 -0.278882   
405   6.695076  14.589819  11.155086  12.120877  ... -0.137804  0.219037   
406  -1.619369   5.730140  -0.494002   1.339382  ... -0.750146 -0.332148   
407  13.840286  15.598841  16.685939  16.156410  ... -0.532082 -0.967079   
408  12.013472   5.876935  10.270261   8.411082  ... -0.110783 -0.978166   

         52_5      53_5      54_5      55_5      56_5      57_5      58_5  \
404  0.193244  0.012365  0.235660 -0.151464 -0.380631 -0.435589 -1.270069   
405 -0.466993 -0.367277 -0.902319 -0.534517 -0.477164 -0.729161 -0.412996   
406 -0.702545 -0.536359 -0.734779 -0.862411 -0.477073 -0.627626 -0.401184   
407 -0.521906 -0.288034 -0.567411 -0.372875  0.702153 -0.470092 -0.401993   
408 -0.028490 -0.543159  0.465730 -0.034057  0.156840 -0.467797 -0.645596   

         59_5  
404 -0.177306  
405 -0.683427  
406 -0.591205  
407 -0.044324  
408 -0.041062  

[5 rows x 360 columns]

In [21]:
df_normalized = (df_concat - df_concat.mean()) / df_concat.std()
df_normalized.head()

0         1         2         3         4         5         6  \
404  0.420594  0.578550  0.026692 -0.634482  0.412892 -0.298805 -0.213531   
405  0.641346  1.296160  0.941187  0.179183  0.727620  0.571391  0.264394   
406 -0.031145  0.208449  0.018957 -0.107448 -0.017011 -0.236679 -0.353785   
407 -0.078801  0.258311  1.392458  0.988147  0.395243  1.204457  0.795640   
408  0.294692 -0.174066  0.349692  1.027007  0.022824  0.544525  0.659817   

            7         8         9  ...      50_5      51_5      52_5  \
404 -0.360818 -0.275056 -0.208658  ...  0.338976  0.074613  0.782792   
405  0.667008  0.546885  0.294406  ...  0.206641  1.015465 -0.234217   
406  0.058576 -0.468587 -0.189941  ... -0.404330 -0.026036 -0.597054   
407  0.736301  1.029019  0.475698  ... -0.186754 -1.225782 -0.318804   
408  0.068657  0.469753  0.127747  ...  0.233602 -1.246732  0.441239   

         53_5      54_5      55_5      56_5      57_5      58_5      59_5  
404  0.608819  0.666479  0.202753 -0.300114 -0.226446 -1.685428  0.035528  
405  0.027702 -0.587630 -0.590719 -0.458191 -0.753147 -0.368397 -0.822553  
406 -0.231111 -0.402993 -1.269931 -0.458042 -0.570981 -0.350247 -0.666200  
407  0.148999 -0.218545 -0.255886  1.472988 -0.288349 -0.351489  0.260988  
408 -0.241520  0.920027  0.445955  0.580015 -0.284232 -0.725825  0.266517  

[5 rows x 360 columns]

In [22]:
from sklearn.svm import LinearSVC
model = LinearSVC(max_iter=10000)

scores = cross_val_score(model, df_normalized, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.50980392 0.42       0.54       0.51020408 0.44897959]
Accuracy: 0.49 (+/- 0.09)


In [23]:
from sklearn.svm import SVC
model = SVC(gamma='scale')

scores = cross_val_score(model, df_concat, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.50980392 0.52       0.56       0.48979592 0.53061224]
Accuracy: 0.52 (+/- 0.05)


In [24]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
scores = cross_val_score(model, df_concat, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.49019608 0.52       0.54       0.48979592 0.44897959]
Accuracy: 0.50 (+/- 0.06)


/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/l