In [1]:
import setup_jwlab
import pandas as pd
import numpy as np

from jwlab.ml_prep import load_ml_df, y_to_binary
from sklearn.model_selection import cross_val_score

In [2]:
df = load_ml_df("~/projects/def-jwerker/kjslakov/data/ml_df_readys.pkl")

In [3]:
y = df.participant.values
y[y < 6] = 0
y[y >= 6] = 1
df = df.drop(columns=["label", "participant"], axis=1)

In [4]:
df.head()

0          1          2          3          4          5      \
0 -13.517964  22.010553  10.012394  21.608709 -47.938713   3.326609   
3  -6.267445 -10.671413   0.578791  11.550019 -22.521195  10.500483   
4  -5.051580 -10.781385   0.190375   1.368724   5.463544   7.725687   
6  -5.336224   8.902582   1.747106  -3.788313   2.612656  -6.873928   
7  14.368332  -7.143710  -1.941029  -4.037873 -16.169552   3.893104   

       6          7          8          9      ...      59990      59991  \
0  16.604320  -2.932594   7.207325 -30.335497  ...  30.628658  -6.693759   
3  21.748081   4.407655  17.857426 -62.065186  ... -17.182715  13.062177   
4  -3.148193  11.126657   9.978209  12.743648  ...  -0.136852  11.134411   
6 -16.138010 -10.887217 -13.439786  -9.340491  ... -30.417248   6.879998   
7  -8.895123   2.405070  -0.573063 -19.320463  ...  -5.275133  27.263466   

       59992      59993      59994      59995      59996      59997     59998  \
0  32.954323  17.554173 -28.639063  18.128828  31.486328  14.813962  9.645177   
3 -16.948093 -15.687716  36.943016   6.545364 -12.206253  28.711948 -3.582610   
4   3.889105   1.637905  -4.101464   7.384897   4.721143   5.155228  1.844576   
6 -26.742655 -20.750853  12.206245   6.021628 -13.380303  16.875305  2.191557   
7  -4.218991 -15.093294  17.519402   5.642640  -7.015842  18.700117 -9.990950   

       59999  
0  29.282951  
3 -13.335809  
4  -2.275076  
6  -8.392258  
7 -17.293606  

[5 rows x 60000 columns]

In [5]:
np.mean(y == 0)

0.5860597439544808

In [6]:
from sklearn.svm import LinearSVC
model = LinearSVC(C=1e-6, max_iter=10000)

scores = cross_val_score(model, df, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.53521127 0.4822695  0.54285714 0.57857143 0.53571429]
Accuracy: 0.53 (+/- 0.06)


In [7]:
from sklearn.svm import SVC
model = SVC(gamma='scale')

scores = cross_val_score(model, df, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.58450704 0.58865248 0.57857143 0.58571429 0.66428571]
Accuracy: 0.60 (+/- 0.06)


In [8]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
scores = cross_val_score(model, df, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/l

[0.55633803 0.4964539  0.58571429 0.58571429 0.62857143]
Accuracy: 0.57 (+/- 0.09)
