In [1]:
import setup_jwlab
import pandas as pd
import numpy as np

from jwlab.ml_prep import load_ml_df, y_to_binary
from sklearn.model_selection import cross_val_score

In [2]:
df = load_ml_df("~/projects/def-jwerker/kjslakov/data/ml_df_readys.pkl")

In [3]:
y = df.participant.values
y[y <= 11] = 0
y[y > 11] = 1
df = df.drop(columns=["label", "participant"], axis=1)

In [4]:
df.head()

0           1           2           3           4           5      \
0   50.449753  138.133133  126.717212  149.367197   36.781255  104.922580   
1  -37.132645  161.466307  156.438376  115.736323  115.471507  108.654233   
2    7.893801   14.047359   22.842200   24.524011  114.983781   28.889022   
3   -4.610002   -9.418404   10.674796   27.730582   84.877453   25.914138   
4 -173.983406 -164.342091 -157.416311  -97.254718 -167.746539 -129.771580   

        6           7           8           9      ...       17990  \
0   55.184135   87.987745  129.338971  -71.151635  ...   78.571593   
1   33.656159  146.176553   99.608679   23.079561  ...   34.940964   
2   54.507082   20.811691   28.713169  -13.137387  ...   31.854351   
3   57.652917   11.320962   31.576525  -52.901394  ... -170.306125   
4 -130.356181 -149.251980 -138.944774 -242.672413  ... -164.324930   

        17991       17992       17993        17994       17995       17996  \
0  171.155626  139.364090  124.335217  -204.489194  145.826677  271.538668   
1  -76.056590   -5.691290   23.843827    36.836227  -49.116065   -5.342957   
2  -30.906935    0.060032   18.255586  -142.465714  -31.275570   -6.219524   
3  -95.309878 -155.809703 -148.276279  1302.220468 -141.464596 -136.894723   
4  -30.746377 -126.832639  -90.449150   956.644648  -78.934968  -90.884256   

        17997       17998       17999  
0  125.980671  180.188476  149.211144  
1  -84.522853    1.558821    3.216763  
2  -61.700972  -13.027648  -20.458329  
3 -165.490097 -161.881650 -160.968116  
4  -61.724444  -87.471211 -101.963853  

[5 rows x 18000 columns]

In [5]:
print(np.mean(y == 0))
print(np.mean(y == 1))

0.36966192170818507
0.630338078291815


In [6]:
df_normalized = (df - df.mean()) / df.std()
df_normalized.head()

0         1         2         3         4         5         6      \
0  0.182637  1.009890  0.836685  0.423567  0.172862  0.591842  0.154484   
1 -0.060863  1.185858  1.043362  0.333873  0.475246  0.612966  0.101836   
2  0.064321  0.074092  0.114352  0.090608  0.473372  0.161437  0.152828   
3  0.029558 -0.102876  0.029741  0.099160  0.357682  0.144597  0.160521   
4 -0.441341 -1.271240 -1.139142 -0.234178 -0.613082 -0.736696 -0.299267   

      7         8         9      ...     17990     17991     17992     17993  \
0  0.208476  0.362994 -0.028128  ...  0.335004  1.044417  0.593482  0.535493   
1  0.379926  0.282175  0.059641  ...  0.137286 -0.455738 -0.046227  0.083394   
2  0.010545  0.089453  0.025908  ...  0.123299 -0.181756 -0.020863  0.058253   
3 -0.017419  0.097237 -0.011129  ... -0.792816 -0.572572 -0.708263 -0.690954   
4 -0.490539 -0.366309 -0.187885  ... -0.765712 -0.180782 -0.580472 -0.430797   

      17994     17995     17996     17997     17998     17999  
0 -0.134397  1.078224  0.533725  0.180141  1.354876  0.734850  
1  0.058854 -0.363320 -0.048108 -0.068268  0.032211 -0.016237  
2 -0.084729 -0.231395 -0.049950 -0.041337 -0.075795 -0.138037  
3  1.072163 -1.046210 -0.324548 -0.163816 -1.177985 -0.860908  
4  0.795429 -0.583822 -0.227863 -0.041365 -0.627013 -0.557353  

[5 rows x 18000 columns]

In [8]:
from sklearn.svm import LinearSVC
model = LinearSVC(C=1e-4)

scores = cross_val_score(model, df_normalized, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[0.57427938 0.51333333 0.40089087 0.57683742 0.48329621]
Accuracy: 0.51 (+/- 0.13)


In [10]:
from sklearn.svm import SVC
model = SVC(gamma='scale')

scores = cross_val_score(model, df, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.62971175 0.63111111 0.61469933 0.71492205 0.63474388]
Accuracy: 0.65 (+/- 0.07)


In [9]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
scores = cross_val_score(model, df, y, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/kjslakov/jupyter_py3/l

[0.52549889 0.66888889 0.78173719 0.75055679 0.57238307]
Accuracy: 0.66 (+/- 0.20)
